version: '3'
services:
  app1:
    container_name: flask_app1
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    networks:
      - work_net
    environment:
      PORT: 8001

  app2:
    container_name: flask_app2
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    networks:
      - work_net
    environment:
      PORT: 8002

  app3:
    container_name: flask_app3
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    networks:
      - work_net
    environment:
      PORT: 8003

  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    restart: always
    container_name: template_nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - work_net

networks:
  work_net:
    driver: bridge